project:
  type: website

website:
  title: Infographic Innovators
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO526-DataViz/project-final-Infographic-Innovators
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd
    logo: images\flight_logo.png
  favicon:  images\flight_logo.png

format:
  html:
    theme:
      dark: darkly
      light: flatly
    toc: true

execute:
  freeze: auto
